version: "3"
services:
  nginx:
    build: ./.docker/nginx
    restart: unless-stopped
    volumes:
      - ./:/var/www/
    ports:
      - "8585:80"
    depends_on:
      - php
      - mysql

  php:
    build: ./.docker/php
    restart: unless-stopped
    volumes:
      - ./:/var/www/
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    restart: unless-stopped
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-connect='SET NAMES utf8mb4;'
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=symariakish
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql

  encore:
    tty: true
    build: ./.docker/encore
    restart: unless-stopped
    volumes:
      - ./:/var/www/
    depends_on:
      - nginx
      - php
      - mysql

networks:
  app_network:
    driver: bridge