version: "3.7"
services:
    # image project
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        image: laravel-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks: 
            - laravel-mohjeranshop
                
    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports: 
            - 8180:80
        volumes: 
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks: 
            - laravel-mohjeranshop

    # db mariadb
    mariadb:
        image: mariadb:latest
        restart: unless-stopped
        environment: 
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes: 
            - ./docker/mysql/dbdata:/var/lib/mysql
        ports: 
            - 3388:3306
        networks: 
            - laravel-mohjeranshop
  
    #PHPMYADMIN  Service
    phpmyadmin:
      container_name: phpmyadmin
      image: phpmyadmin/phpmyadmin:latest
      environment:
        - PMA_HOST=mariadb
        - PMA_USER=${DB_USERNAME}
        - PMA_PASSWORD=${DB_PASSWORD}
        - UPLOAD_LIMIT= 102400000000
      restart: always
      ports:
        - 8181:80
      networks:
        - laravel-mohjeranshop

networks:
    laravel-mohjeranshop:
        driver: bridge