FROM php:8.1.18-fpm

RUN apt-get update && apt-get install -y \
        libicu-dev \
        curl \
        git \
        unzip \
        nano \
    && docker-php-ext-install \
        intl \
        opcache \
    && docker-php-ext-enable \
        intl \
        opcache

# Source code
RUN chown www-data:www-data /var/www
COPY --chown=www-data:www-data ./ /var/www
WORKDIR /var/www

USER www-data

# Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

ENV COMPOSER_ALLOW_SUPERUSER=1

ENV PHP_OPCACHE_VALIDATE_TIMESTAMPS="0"
COPY ./php.ini /usr/local/etc/php/conf.d/docker-php-config.ini

RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash - \
    && apt-get install -y nodejs \
    && npm -g install yarn

EXPOSE 9000
CMD ["php-fpm"]