FROM php:8.0-fpm

RUN apt-get update && apt-get install -y \
        libicu-dev \
        curl \
        git \
        unzip \
        nano \
    && docker-php-ext-install \
        intl \
        opcache \
    && docker-php-ext-enable \
        intl \
        opcache

RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
    && php composer-setup.php \
    && php -r "unlink('composer-setup.php');" \
    && mv composer.phar /usr/local/bin/composer

RUN curl -sS https://get.symfony.com/cli/installer | bash \
    && mv /root/.symfony5/bin/symfony /usr/local/bin/symfony

ENV COMPOSER_ALLOW_SUPERUSER=1

RUN cd /var/www && \
    composer install

ENV PHP_OPCACHE_VALIDATE_TIMESTAMPS="0"
COPY ./php.ini /usr/local/etc/php/conf.d/docker-php-config.ini

RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash - \
    && apt-get install -y nodejs \
    && npm -g install yarn

EXPOSE 9000
CMD ["php-fpm"]